# Generated by Django 3.2.5 on 2023-04-02 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.TextField(blank=True, default=None, null=True)),
                ('card_name', models.TextField(blank=True, default=None, null=True)),
                ('card_type', models.TextField(blank=True, default=None, null=True)),
                ('card_action', models.TextField(blank=True, default=None, null=True)),
                ('card_value', models.TextField(blank=True, default=None, null=True)),
                ('card_color', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.cards')),
            ],
        ),
    ]
