# Generated by Django 3.2.5 on 2023-03-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20230326_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='luckycard',
            name='card_id',
            field=models.TextField(default=None, null=True, unique=True, verbose_name='Kart ID'),
        ),
    ]
