# Generated by Django 3.2.5 on 2023-04-02 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.cards'),
        ),
    ]
