# Generated by Django 3.2.5 on 2023-04-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_players_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='color',
            field=models.TextField(blank=True, default='green', null=True),
        ),
    ]
